spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    redis:
      host: localhost    # 修改这里，本地开发时使用 localhost
      port: 6379
      password: ""
      timeout: 10000    # 添加超时配置
  cache:
    type: redis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  # 已经启用了，很好
#设置输出日志级别
logging:
  level:
    org.springframework.web: DEBUG
    org:
      springframework:
        security: DEBUG
    org.mybatis: INFO
    com.cxzcanying.winterproject: DEBUG
#阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-chengdu.aliyuncs.com
    accessKeyId: LTAI5tAae5c33H8pTCMRq5g4
    accessKeySecret: S6xVr2LWsf5yEXtd1lUqIZ5szJNQNo
    bucketName: springbot
jwt:
  secret-key: u6xfPEz4fn6SJN2JE0+MxEp1kNPTJaFAlAjjpc2j3hI=